version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/yashodhamart?sslmode=disable
      - JWT_SECRET=yashodha_mart_super_secret_jwt_key_2026_college_project_secure_session
      - NODE_ENV=production
      - PAYMENT_UPI_ID=demo-yashodhamart@okhdfcbank
      - PORT=3000
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yashodhamart
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
