import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

// 20 Major Categories and their subcategories
interface SubcategoryDef {
  name: string;
  slug: string;
  description: string;
}

interface CategoryDef {
  name: string;
  slug: string;
  description: string;
  image: string;
  subcategories: SubcategoryDef[];
}

const CATEGORIES_DATA: CategoryDef[] = [
  {
    name: 'Grocery',
    slug: 'grocery',
    description: 'Daily Indian grocery staples, organic spices, pulses, rice, flours and pantry foods',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=600',
    subcategories: [
      { name: 'Rice & Grains', slug: 'rice-grains', description: 'Basmati rice, sona masoori, brown rice & millets' },
      { name: 'Atta & Flour', slug: 'atta-flour', description: 'Whole wheat chakki atta, besan, maida & multigrain flour' },
      { name: 'Pulses & Dal', slug: 'pulses-dal', description: 'Toor dal, moong dal, chana dal & rajma' },
      { name: 'Cooking Oil', slug: 'cooking-oil', description: 'Mustard oil, sunflower oil, olive oil & pure desi ghee' },
      { name: 'Spices & Masala', slug: 'spices-masala', description: 'Haldi, mirchi, garam masala & whole organic spices' },
      { name: 'Salt & Sugar', slug: 'salt-sugar', description: 'Iodized salt, rock salt, cane sugar & organic jaggery' },
      { name: 'Dry Fruits & Nuts', slug: 'dry-fruits-nuts', description: 'Almonds, cashews, raisins, walnuts & pista' },
      { name: 'Snacks', slug: 'snacks', description: 'Namkeen, bhujia, roasted makhana & chips' },
      { name: 'Biscuits', slug: 'biscuits', description: 'Digestive, butter cookies, glucose & cream biscuits' },
      { name: 'Chocolates', slug: 'chocolates', description: 'Dark chocolate bars, gifting boxes & chocolate spreads' },
      { name: 'Tea', slug: 'tea', description: 'Assam CTC tea, Darjeeling green tea & masala chai' },
      { name: 'Coffee', slug: 'coffee', description: 'South Indian filter coffee, instant coffee & roast beans' },
      { name: 'Breakfast Foods', slug: 'breakfast-foods', description: 'Corn flakes, oats, muesli & poha' },
      { name: 'Packaged Foods', slug: 'packaged-foods', description: 'Noodles, pasta, ready-to-eat curries & papad' },
      { name: 'Beverages', slug: 'beverages', description: 'Fruit juices, herbal syrups, squash & coconut water' },
      { name: 'Sauces & Spreads', slug: 'sauces-spreads', description: 'Tomato ketchup, schezwan sauce, peanut butter & honey' },
    ],
  },
  {
    name: 'Fruits & Vegetables',
    slug: 'fruits-vegetables',
    description: 'Farm fresh seasonal fruits, green vegetables, herbs and certified organic produce',
    image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&q=80&w=600',
    subcategories: [
      { name: 'Fresh Fruits', slug: 'fresh-fruits', description: 'Apples, bananas, mangoes, oranges & pomegranates' },
      { name: 'Fresh Vegetables', slug: 'fresh-vegetables', description: 'Potatoes, onions, tomatoes, bhindi & cauliflower' },
      { name: 'Leafy Vegetables', slug: 'leafy-vegetables', description: 'Palak, methi, coriander leaves & fresh mint' },
      { name: 'Organic Products', slug: 'organic-produce', description: 'Certified chemical-free naturally ripened farm produce' },
    ],
  },
  {
    name: 'Dairy & Bakery',
    slug: 'dairy-bakery',
    description: 'Fresh cow milk, curd, paneer, artisanal bread, butter, cheese and fresh cakes',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&q=80&w=600',
    subcategories: [
      { name: 'Milk', slug: 'dairy-milk', description: 'Toned milk, full cream milk, cow milk & almond milk' },
      { name: 'Curd', slug: 'dairy-curd', description: 'Fresh dahi, Greek yogurt & spiced buttermilk' },
      { name: 'Butter', slug: 'dairy-butter', description: 'Salted table butter, white makkhan & garlic herb butter' },
      { name: 'Cheese', slug: 'dairy-cheese', description: 'Processed cheese blocks, mozzarella & cheese slices' },
      { name: 'Paneer', slug: 'dairy-paneer', description: 'Fresh malai paneer, organic tofu & cottage cheese' },
      { name: 'Bread', slug: 'bakery-bread', description: 'Whole wheat bread, brown bread & multi-grain loaves' },
      { name: 'Cakes', slug: 'bakery-cakes', description: 'Fresh plum cakes, truffle pastries & birthday cakes' },
      { name: 'Bakery Items', slug: 'bakery-items', description: 'Rusk, khari biscuits, cookies & puffs' },
    ],
  },
  {
    name: 'Electronics',
    slug: 'electronics',
    description: 'Smartphones, tablets, high-performance laptops, monitors, smartwatches and gadgets',
    image: 'https://images.unsplash.com/photo-1498049860654-af1a5c566876?auto=format&fit=crop&q=80&w=600',
    subcategories: [
      { name: 'Mobiles', slug: 'mobiles', description: '5G Android smartphones & flagship mobile devices' },
      { name: 'Tablets', slug: 'tablets', description: 'iPad, Android tablets & student learning slates' },
      { name: 'Laptops', slug: 'laptops', description: 'Core i5/i7 ultrabooks, gaming laptops & workbooks' },
      { name: 'Computers', slug: 'computers', description: 'All-in-one desktop systems & CPU towers' },
      { name: 'Monitors', slug: 'monitors', description: 'Full HD & 4K IPS frameless computer monitors' },
      { name: 'Printers', slug: 'printers', description: 'All-in-one ink tank & wireless laser printers' },
      { name: 'Cameras', slug: 'cameras', description: 'DSLR, mirrorless vlog cameras & security cameras' },
      { name: 'Headphones', slug: 'headphones', description: 'Over-ear noise cancelling wireless headphones' },
      { name: 'Speakers', slug: 'speakers', description: 'Bluetooth portable party speakers & home soundbars' },
      { name: 'Smart Watches', slug: 'smart-watches', description: 'Fitness trackers with heart-rate & calling' },
      { name: 'Smart Devices', slug: 'smart-devices', description: 'Smart plugs, voice assistants & smart bulbs' },
    ],
  },
  {
    name: 'Mobile Accessories',
    slug: 'mobile-accessories',
    description: 'Durable phone covers, tempered glasses, fast chargers, power banks and cables',
    image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&q=80&w=600',
    subcategories: [
      { name: 'Mobile Cases', slug: 'mobile-cases', description: 'Shockproof bumper cases, leather flip & silicone covers' },
      { name: 'Screen Protectors', slug: 'screen-protectors', description: '9H tempered glass, privacy glass & matte film' },
      { name: 'Chargers', slug: 'chargers', description: 'GaN 65W fast adapters, wireless charging pads' },
      { name: 'USB Cables', slug: 'usb-cables', description: 'Braided Type-C, Lightning & micro-USB fast cables' },
      { name: 'Power Banks', slug: 'power-banks', description: '10000mAh - 20000mAh quick charge power banks' },
      { name: 'Earphones', slug: 'earphones', description: 'In-ear wired 3.5mm & Type-C high bass earphones' },
      { name: 'Mobile Stands', slug: 'mobile-stands', description: 'Adjustable metal desk stands & ring holders' },
      { name: 'Car Chargers', slug: 'car-chargers', description: 'Dual port fast car cigarette lighter adapters' },
    ],
  },
  {
    name: 'Fashion',
    slug: 'fashion',
    description: 'Trending ethnic wear, cotton kurtis, sarees, formal shirts, dresses and casual jeans',
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&q=80&w=600',
    subcategories: [
      { name: "Men's Clothing", slug: 'mens-clothing', description: 'Casual shirts, trousers, chinos & polo tees' },
      { name: "Women's Clothing", slug: 'womens-clothing', description: 'Tops, dresses, denim, skirts & loungewear' },
      { name: 'Kids Clothing', slug: 'kids-clothing', description: 'Comfortable cotton dresses & boys sets' },
      { name: 'Sarees', slug: 'sarees', description: 'Banarasi, Kanjivaram silk, cotton & chiffon sarees' },
      { name: 'Kurtis', slug: 'kurtis', description: 'Anarkali kurtas, straight fit & printed designer kurtis' },
      { name: 'T-Shirts', slug: 't-shirts', description: 'Crew neck, graphic prints, oversized & round neck tees' },
      { name: 'Shirts', slug: 'shirts', description: 'Formal office wear & casual checks shirts' },
      { name: 'Jeans', slug: 'jeans', description: 'Slim fit, straight leg, stretch & high-waist denim' },
      { name: 'Dresses', slug: 'dresses', description: 'Maxi dresses, midi gowns & festive western dresses' },
      { name: 'Ethnic Wear', slug: 'ethnic-wear', description: 'Sherwanis, lehenga cholis & traditional dhotis' },
      { name: 'Winter Wear', slug: 'winter-wear', description: 'Cardigans, hoodies, sweaters & warm jackets' },
      { name: 'Innerwear', slug: 'innerwear', description: 'Breathable cotton vests, briefs & lounge shorts' },
    ],
  },
  {
    name: 'Footwear',
    slug: 'footwear',
    description: 'Athletic running shoes, formal shoes, ethnic sandals, loafers and daily slippers',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=600',
    subcategories: [
      { name: "Men's Shoes", slug: 'mens-shoes', description: 'Formal leather oxfords, derbies & monk straps' },
      { name: "Women's Shoes", slug: 'womens-shoes', description: 'Heels, wedges, formal pumps & ballerinas' },
      { name: 'Kids Shoes', slug: 'kids-shoes', description: 'Velcro school shoes, sports runners & boots' },
      { name: 'Sandals', slug: 'sandals', description: 'Ethnic kolhapuris, roman sandals & floaters' },
      { name: 'Slippers', slug: 'slippers', description: 'Memory foam flip flops, slides & bath chappals' },
      { name: 'Sports Shoes', slug: 'sports-shoes', description: 'Cushioned running shoes, gym training & court shoes' },
      { name: 'Casual Shoes', slug: 'casual-shoes', description: 'Canvas sneakers, slip-on shoes & deck shoes' },
    ],
  },
  {
    name: 'Beauty & Personal Care',
    slug: 'beauty-personal-care',
    description: 'Ayurvedic skincare, haircare, makeup essentials, bath soaps and personal grooming',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=600',
    subcategories: [
      { name: 'Skin Care', slug: 'skin-care', description: 'Moisturizers, vitamin serums, sunscreens & face wash' },
      { name: 'Hair Care', slug: 'hair-care', description: 'Herbal shampoos, conditioners, onion oil & hair masks' },
      { name: 'Makeup', slug: 'makeup', description: 'Kajals, lipsticks, foundations, compact & eyeliner' },
      { name: 'Fragrances', slug: 'fragrances', description: 'Attars, long-lasting perfumes & fresh body mists' },
      { name: 'Bath & Body', slug: 'bath-body', description: 'Handcrafted soaps, body washes & loofahs' },
      { name: 'Oral Care', slug: 'oral-care', description: 'Bamboo toothbrushes, herbal toothpaste & mouthwash' },
      { name: 'Personal Hygiene', slug: 'personal-hygiene', description: 'Hand sanitizers, face wipes & hygiene essentials' },
    ],
  },
  {
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    description: 'Non-stick cookware, stainless steel dinnerware, bedding, decor and storage',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=600',
    subcategories: [
      { name: 'Kitchen Appliances', slug: 'kitchen-appliances', description: 'Toasters, electric kettles & hand blenders' },
      { name: 'Cookware', slug: 'cookware', description: 'Granite tawas, kadhais, fry pans & pressure cookers' },
      { name: 'Dinnerware', slug: 'dinnerware', description: 'Opalware sets, ceramic bowls, thalis & mugs' },
      { name: 'Storage & Organization', slug: 'storage-organization', description: 'Airtight containers, spice boxes & racks' },
      { name: 'Home Decor', slug: 'home-decor', description: 'Wall paintings, clocks, vases & artificial plants' },
      { name: 'Furniture', slug: 'furniture', description: 'Ergonomic study chairs, coffee tables & shoe racks' },
      { name: 'Cleaning Supplies', slug: 'cleaning-supplies', description: 'Floor cleaners, microfiber mops & dishwashing liquid' },
      { name: 'Bathroom Accessories', slug: 'bathroom-accessories', description: 'Towel sets, soap dispensers & shower curtains' },
      { name: 'Home Furnishing', slug: 'home-furnishing', description: 'Pure cotton bedsheets, curtains & cushion covers' },
    ],
  },
  {
    name: 'Appliances',
    slug: 'appliances',
    description: 'Smart refrigerators, washing machines, inverter ACs, microwave ovens and mixers',
    image: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&q=80&w=600',
    subcategories: [
      { name: 'Refrigerators', slug: 'refrigerators', description: 'Single door, double door & frost-free fridges' },
      { name: 'Washing Machines', slug: 'washing-machines', description: 'Top load, front load & semi-automatic washers' },
      { name: 'Air Conditioners', slug: 'air-conditioners', description: '1.5 ton 5-star split & inverter air conditioners' },
      { name: 'Fans', slug: 'fans', description: 'BLDC energy-saving ceiling fans & table fans' },
      { name: 'Microwave Ovens', slug: 'microwave-ovens', description: 'Convection, grill & solo microwave ovens' },
      { name: 'Mixers & Grinders', slug: 'mixers-grinders', description: '750W 3-jar stainless steel mixer grinders' },
      { name: 'Electric Cookers', slug: 'electric-cookers', description: 'Rice cookers, induction cooktops & slow cookers' },
      { name: 'Irons', slug: 'irons', description: 'Dry irons, steam press irons & garment steamers' },
      { name: 'Vacuum Cleaners', slug: 'vacuum-cleaners', description: 'Robotic vacuums, wet & dry drum vacuum cleaners' },
    ],
  },
  {
    name: 'Books',
    slug: 'books',
    description: 'UPSC competitive exam textbooks, bestselling Indian fiction, self-help and tech books',
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=600',
    subcategories: [
      { name: 'Academic Books', slug: 'academic-books', description: 'NCERT, CBSE & university syllabus coursebooks' },
      { name: 'Competitive Exam Books', slug: 'competitive-exam-books', description: 'UPSC, SSC, Banking, JEE & NEET prep guides' },
      { name: 'Fiction', slug: 'fiction-books', description: 'Indian thrillers, classic literature & sci-fi novels' },
      { name: 'Non-Fiction', slug: 'non-fiction-books', description: 'Biographies, history, self-help & productivity' },
      { name: "Children's Books", slug: 'childrens-books', description: 'Panchatantra, picture story books & rhymes' },
      { name: 'Computer & Technology', slug: 'computer-tech-books', description: 'Python, DSA, Web dev & AI engineering guides' },
      { name: 'Engineering Books', slug: 'engineering-books', description: 'Mechanical, electrical & civil engineering textbooks' },
    ],
  },
  {
    name: 'Stationery',
    slug: 'stationery',
    description: 'School notebooks, gel pens, drafting geometry sets, art materials and office stationery',
    image: 'https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?auto=format&fit=crop&q=80&w=600',
    subcategories: [
      { name: 'Notebooks', slug: 'notebooks', description: 'Spiral bound, ruled long books & executive diaries' },
      { name: 'Pens', slug: 'pens', description: 'Gel pens, ball pens, fountain pens & fine-liners' },
      { name: 'Pencils', slug: 'pencils', description: 'Graphite sketching pencils & mechanical drafting pencils' },
      { name: 'School Supplies', slug: 'school-supplies', description: 'Geometry boxes, compasses, erasers & sharpeners' },
      { name: 'Office Supplies', slug: 'office-supplies', description: 'Staplers, punching machines, calculators & desk organizers' },
      { name: 'Art Supplies', slug: 'art-supplies', description: 'Acrylic colours, watercolour sketchbooks & canvas panels' },
      { name: 'Bags', slug: 'school-office-bags', description: 'Ergonomic school bags, college satchels & file bags' },
    ],
  },
  {
    name: 'Toys & Games',
    slug: 'toys-games',
    description: 'STEM building blocks, traditional Indian board games, puzzles and RC hobby toys',
    image: 'https://images.unsplash.com/photo-1558060370-d644479cb6f7?auto=format&fit=crop&q=80&w=600',
    subcategories: [
      { name: 'Educational Toys', slug: 'educational-toys', description: 'Robotics kits, solar projects & science experiments' },
      { name: 'Board Games', slug: 'board-games', description: 'Chess, Carrom boards, Ludo & Monopoly India' },
      { name: 'Puzzles', slug: 'puzzles', description: 'Jigsaw puzzles, Rubik’s cubes & wooden brain teasers' },
      { name: 'Remote Control Toys', slug: 'rc-toys', description: 'RC stunt cars, quadcopter drones & RC helicopters' },
      { name: 'Outdoor Games', slug: 'outdoor-games', description: 'Frisbees, skipping ropes & dart boards' },
      { name: 'Baby Toys', slug: 'baby-toys-early', description: 'Teethers, rattle sets, soft plush teddies & musical toys' },
    ],
  },
  {
    name: 'Baby Products',
    slug: 'baby-products',
    description: 'Gentle cotton babywear, milk formula, soft diapers, feeding accessories and bath care',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=600',
    subcategories: [
      { name: 'Baby Clothing', slug: 'baby-clothing', description: 'Soft organic cotton onesies, rompers & mittens' },
      { name: 'Baby Food', slug: 'baby-food', description: 'Infant cereals, fruit purées & teething biscuits' },
      { name: 'Diapers', slug: 'baby-diapers', description: 'Pant style leakproof diapers & pure water wet wipes' },
      { name: 'Baby Care', slug: 'baby-care', description: 'Tear-free wash, rash cream, baby powder & massage oil' },
      { name: 'Feeding Accessories', slug: 'feeding-accessories', description: 'BPA-free bottles, sippers, bibs & sterilizers' },
      { name: 'Baby Toys', slug: 'baby-toys', description: 'Crib mobiles, sensory rattles & cloth books' },
    ],
  },
  {
    name: 'Sports & Fitness',
    slug: 'sports-fitness',
    description: 'Cricket gear, yoga mats, hex dumbbells, badminton sets, footballs and cycling accessories',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=600',
    subcategories: [
      { name: 'Sports Equipment', slug: 'sports-equipment', description: 'Equipment bags, cones, stopwatches & whistles' },
      { name: 'Fitness Equipment', slug: 'fitness-equipment', description: 'Hex dumbbells, resistance bands & pull-up bars' },
      { name: 'Yoga', slug: 'yoga-fitness', description: 'Eco-friendly TPE yoga mats, yoga blocks & straps' },
      { name: 'Cricket', slug: 'cricket-gear', description: 'Kashmir willow bats, leather balls, batting pads & gloves' },
      { name: 'Football', slug: 'football-gear', description: 'Size 5 match balls, goalkeeper gloves & shin guards' },
      { name: 'Badminton', slug: 'badminton-gear', description: 'High-tension rackets, feather shuttles & kit bags' },
      { name: 'Cycling Accessories', slug: 'cycling-accessories', description: 'Cycle helmets, LED headlamps, locks & air pumps' },
    ],
  },
  {
    name: 'Jewellery & Accessories',
    slug: 'jewellery-accessories',
    description: 'Ethnic gold-plated necklaces, silver rings, watches, leather wallets and polarized shades',
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&q=80&w=600',
    subcategories: [
      { name: 'Earrings', slug: 'jewellery-earrings', description: 'Jhumkas, chandbalis, studs & drop earrings' },
      { name: 'Necklaces', slug: 'jewellery-necklaces', description: 'Kundan choker sets, temple jewellery & chains' },
      { name: 'Bracelets', slug: 'jewellery-bracelets', description: 'Kada bangles, tennis bracelets & charm cuffs' },
      { name: 'Rings', slug: 'jewellery-rings', description: 'Adjustable solitaire rings & silver bands' },
      { name: 'Watches', slug: 'jewellery-watches', description: 'Analog quartz, chronograph & rose gold dial watches' },
      { name: 'Handbags', slug: 'jewellery-handbags', description: 'Tote bags, crossbody slings & ethnic potli bags' },
      { name: 'Wallets', slug: 'jewellery-wallets', description: 'Genuine leather RFID bi-fold wallets & clutches' },
      { name: 'Sunglasses', slug: 'jewellery-sunglasses', description: 'Aviators, wayfarers & UV400 polarized shades' },
    ],
  },
  {
    name: 'Automotive',
    slug: 'automotive',
    description: 'All-weather car mats, bike helmets, vehicle detailing wax, chargers and emergency tools',
    image: 'https://images.unsplash.com/photo-1489824904134-891ab64532f1?auto=format&fit=crop&q=80&w=600',
    subcategories: [
      { name: 'Car Accessories', slug: 'car-accessories', description: '7D car foot mats, seat cushions & mobile mounts' },
      { name: 'Bike Accessories', slug: 'bike-accessories', description: 'Waterproof mobile holder, bike covers & saddle bags' },
      { name: 'Car Care', slug: 'car-care', description: 'Carnauba wax, microfiber towels & shampoo' },
      { name: 'Bike Care', slug: 'bike-care', description: 'Chain lube, chain cleaner & spray polish' },
      { name: 'Helmets', slug: 'helmets', description: 'ISI & DOT certified full face & open face helmets' },
      { name: 'Vehicle Electronics', slug: 'vehicle-electronics', description: 'Dashcams, tire inflators & jump starters' },
    ],
  },
  {
    name: 'Home Improvement',
    slug: 'home-improvement',
    description: 'DIY tool sets, surge protectors, LED lighting, hardware, sanitary fittings and garden tools',
    image: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&q=80&w=600',
    subcategories: [
      { name: 'Tools', slug: 'diy-tools', description: 'Screwdriver sets, hammer, pliers & drilling machines' },
      { name: 'Electrical Supplies', slug: 'electrical-supplies', description: 'Spike guard extension boards, switches & tester pens' },
      { name: 'Hardware', slug: 'hardware-fixtures', description: 'Door locks, hinges, curtain brackets & heavy screws' },
      { name: 'Lighting', slug: 'lighting-fixtures', description: 'B22 LED bulbs, motion sensor lights & decorative strips' },
      { name: 'Gardening', slug: 'gardening-supplies', description: 'Pruners, watering cans, organic vermicompost & planters' },
    ],
  },
  {
    name: 'Pet Supplies',
    slug: 'pet-supplies',
    description: 'Nutritious dog food, cat food, chew toys, grooming brushes and pet shampoos',
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=600',
    subcategories: [
      { name: 'Dog Supplies', slug: 'dog-supplies', description: 'Leashes, harnesses, stainless steel bowls & beds' },
      { name: 'Cat Supplies', slug: 'cat-supplies', description: 'Cat scratchers, litter trays & teaser toys' },
      { name: 'Pet Food', slug: 'pet-food', description: 'Chicken dry kibble, wet gravy pouches & dental treats' },
      { name: 'Pet Toys', slug: 'pet-toys', description: 'Rubber chew balls, squeaker ropes & catnip toys' },
      { name: 'Pet Grooming', slug: 'pet-grooming', description: 'Deshedding combs, nail clippers & herbal neem shampoo' },
    ],
  },
  {
    name: 'Travel',
    slug: 'travel',
    description: 'Durable trekking backpacks, polycarbonate trolley suitcases and travel organizers',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=600',
    subcategories: [
      { name: 'Backpacks', slug: 'travel-backpacks', description: '35L water-resistant hiking rucksacks & daypacks' },
      { name: 'Suitcases', slug: 'travel-suitcases', description: 'Hard-case polycarbonate 4-wheel spinner luggage sets' },
      { name: 'Travel Accessories', slug: 'travel-accessories', description: 'Universal travel adapters, neck pillows & eye masks' },
      { name: 'Travel Organizers', slug: 'travel-organizers', description: '6-piece compression packing cubes & toiletry pouches' },
    ],
  },
];

// Helper to seed 105+ products across all 20 categories
const PRODUCTS_DATA = [
  // 1. GROCERY
  {
    name: 'India Gate Classic Aged Basmati Rice (5kg)',
    slug: 'india-gate-classic-basmati-rice-5kg',
    categorySlug: 'grocery',
    subcategorySlug: 'rice-grains',
    description: 'Authentic aromatic long-grain aged basmati rice. Ideal for biryanis, pulao, and festive Indian dining.',
    price: 649,
    discountPercent: 15,
    stock: 60,
    rating: 4.8,
    reviewCount: 340,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Aashirvaad Superior MP Shudh Chakki Whole Wheat Atta (10kg)',
    slug: 'aashirvaad-mp-chakki-atta-10kg',
    categorySlug: 'grocery',
    subcategorySlug: 'atta-flour',
    description: '100% pure whole wheat ground using traditional stone chakki. Yields extra soft, fluffy, and nutritious rotis.',
    price: 499,
    discountPercent: 10,
    stock: 80,
    rating: 4.7,
    reviewCount: 520,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1627662236973-4fd8358fa206?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Tata Sampann Unpolished High Protein Toor Dal (1kg)',
    slug: 'tata-sampann-toor-dal-1kg',
    categorySlug: 'grocery',
    subcategorySlug: 'pulses-dal',
    description: 'Naturally unpolished Indian Arhar / Toor Dal, retaining natural wholesome nutrients and natural aroma.',
    price: 195,
    discountPercent: 12,
    stock: 120,
    rating: 4.6,
    reviewCount: 215,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1585994192701-f1a505c817ea?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Fortune Sunlite 100% Refined Sunflower Cooking Oil (1L Pouch)',
    slug: 'fortune-sunlite-sunflower-oil-1l',
    categorySlug: 'grocery',
    subcategorySlug: 'cooking-oil',
    description: 'Light, healthy cooking oil enriched with Vitamins A & D. Low absorption formula for crispy snacks and daily food.',
    price: 155,
    discountPercent: 8,
    stock: 95,
    rating: 4.5,
    reviewCount: 180,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Happilo 100% Natural Californian Almonds (500g Value Pack)',
    slug: 'happilo-californian-almonds-500g',
    categorySlug: 'grocery',
    subcategorySlug: 'dry-fruits-nuts',
    description: 'Crunchy, handpicked raw California almonds packed with protein, vitamin E, and dietary fibre. Gluten-free and non-GMO.',
    price: 520,
    discountPercent: 25,
    stock: 45,
    rating: 4.8,
    reviewCount: 410,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1508061252445-564467e24f91?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Tata Tea Gold Premium Assam Long Leaf Black Tea (500g)',
    slug: 'tata-tea-gold-premium-assam-500g',
    categorySlug: 'grocery',
    subcategorySlug: 'tea',
    description: 'An exquisite blend of gently rolled Assam CTC tea with 15% long tea leaves for an irresistible aroma and rich taste.',
    price: 320,
    discountPercent: 15,
    stock: 70,
    rating: 4.7,
    reviewCount: 290,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=800'],
  },

  // 2. FRUITS & VEGETABLES
  {
    name: 'Fresh Kashmiri Red Delicious Crisp Apples (1kg Box)',
    slug: 'fresh-kashmiri-crisp-apples-1kg',
    categorySlug: 'fruits-vegetables',
    subcategorySlug: 'fresh-fruits',
    description: 'Handpicked from the orchards of Srinagar. Sweet, juicy, and crisp texture with deep natural crimson color.',
    price: 180,
    discountPercent: 20,
    stock: 40,
    rating: 4.6,
    reviewCount: 145,
    isFeatured: true,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Farm Fresh Organic Palak / Baby Spinach Leaves (250g)',
    slug: 'farm-fresh-organic-palak-250g',
    categorySlug: 'fruits-vegetables',
    subcategorySlug: 'leafy-vegetables',
    description: 'Tender, washed and pesticide-free hydroponic green spinach leaves rich in iron and essential minerals.',
    price: 35,
    discountPercent: 10,
    stock: 50,
    rating: 4.5,
    reviewCount: 92,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Naturally Ripened Ratnagiri Alphonso Mangoes (1 Dozen)',
    slug: 'ratnagiri-alphonso-mangoes-1-dozen',
    categorySlug: 'fruits-vegetables',
    subcategorySlug: 'organic-produce',
    description: 'GI-tagged authentic GI Ratnagiri Hapus mangoes. Naturally straw-ripened without artificial chemicals.',
    price: 1299,
    discountPercent: 15,
    stock: 25,
    rating: 4.9,
    reviewCount: 210,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Fresh Hybrid Vine Red Tomatoes (1kg)',
    slug: 'fresh-hybrid-red-tomatoes-1kg',
    categorySlug: 'fruits-vegetables',
    subcategorySlug: 'fresh-vegetables',
    description: 'Firm, juicy red tomatoes sourced directly from local contract farmers. Perfect for Indian curries and fresh salads.',
    price: 45,
    discountPercent: 5,
    stock: 90,
    rating: 4.4,
    reviewCount: 88,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Fresh Green Shimla Mirch / Bell Peppers (500g)',
    slug: 'fresh-green-shimla-mirch-500g',
    categorySlug: 'fruits-vegetables',
    subcategorySlug: 'fresh-vegetables',
    description: 'Crisp green capsicums packed with vitamins A and C. Great for stuffing, stir-fries, noodles, and tandoori sizzlers.',
    price: 55,
    discountPercent: 10,
    stock: 65,
    rating: 4.3,
    reviewCount: 64,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&q=80&w=800'],
  },

  // 3. DAIRY & BAKERY
  {
    name: 'Amul Pure Pasteurised Table Butter (500g Block)',
    slug: 'amul-pasteurised-table-butter-500g',
    categorySlug: 'dairy-bakery',
    subcategorySlug: 'dairy-butter',
    description: 'The taste of India. Classic salted butter made from fresh cream. Unmatched richness for parathas, toast, and baking.',
    price: 275,
    discountPercent: 5,
    stock: 55,
    rating: 4.9,
    reviewCount: 680,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Mother Dairy Fresh Soft Malai Paneer (200g)',
    slug: 'mother-dairy-fresh-malai-paneer-200g',
    categorySlug: 'dairy-bakery',
    subcategorySlug: 'dairy-paneer',
    description: 'Melt-in-mouth soft Indian cottage cheese. High in milk protein, hygienic vacuum packaging preserves freshness.',
    price: 92,
    discountPercent: 8,
    stock: 70,
    rating: 4.7,
    reviewCount: 310,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Britannia 100% Whole Wheat Brown Bread (400g Loaf)',
    slug: 'britannia-100-whole-wheat-bread-400g',
    categorySlug: 'dairy-bakery',
    subcategorySlug: 'bakery-bread',
    description: 'Zero maida whole wheat daily bread with dietary fiber. Soft slices perfect for morning breakfast sandwiches.',
    price: 55,
    discountPercent: 5,
    stock: 60,
    rating: 4.5,
    reviewCount: 190,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Artisanal Rich Dark Belgian Truffle Pastry (Pack of 2)',
    slug: 'belgian-dark-truffle-pastry-pack-2',
    categorySlug: 'dairy-bakery',
    subcategorySlug: 'bakery-cakes',
    description: 'Decadent multi-layered Belgian chocolate sponge cake with smooth dark ganache and chocolate curls on top.',
    price: 249,
    discountPercent: 20,
    stock: 30,
    rating: 4.8,
    reviewCount: 110,
    isFeatured: true,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Amul Taaza Homogenised Toned Milk (1 Litre Tetra Pak)',
    slug: 'amul-taaza-toned-milk-1l',
    categorySlug: 'dairy-bakery',
    subcategorySlug: 'dairy-milk',
    description: 'UHT treated long-life pure toned milk. Zero preservatives needed, safe and ready to drink straight from the pack.',
    price: 74,
    discountPercent: 4,
    stock: 85,
    rating: 4.8,
    reviewCount: 420,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=800'],
  },

  // 4. ELECTRONICS
  {
    name: 'Yashodha Neo 5G Dual SIM Smartphone (8GB RAM, 128GB)',
    slug: 'yashodha-neo-5g-smartphone-128gb',
    categorySlug: 'electronics',
    subcategorySlug: 'mobiles',
    description: 'Powered by 6nm Dimensity 7050 5G processor, 6.7" 120Hz AMOLED display, 64MP OIS camera, and 5000mAh battery with 67W SuperVOOC charging.',
    price: 19999,
    discountPercent: 20,
    stock: 35,
    rating: 4.7,
    reviewCount: 240,
    isFeatured: true,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Ultra-Slim 15.6" Full HD Student Laptop (Intel Core i5, 16GB)',
    slug: 'ultraslim-student-laptop-15-inch',
    categorySlug: 'electronics',
    subcategorySlug: 'laptops',
    description: '12th Gen Intel Core i5 processor, 16GB DDR4 RAM, 512GB NVMe SSD, backlit keyboard, Windows 11 Home, and anti-glare display.',
    price: 48999,
    discountPercent: 18,
    stock: 15,
    rating: 4.6,
    reviewCount: 85,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Active Noise Cancelling Wireless Over-Ear Headphones',
    slug: 'anc-wireless-headphones-hd',
    categorySlug: 'electronics',
    subcategorySlug: 'headphones',
    description: '40mm dynamic drivers, hybrid ANC reducing 95% of background noise, 40-hour playtime, and ultra-soft memory foam ear cushions.',
    price: 4999,
    discountPercent: 25,
    stock: 28,
    rating: 4.8,
    reviewCount: 320,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: '27-inch 4K UHD Frameless IPS Computer Monitor (75Hz, HDR)',
    slug: '27-inch-4k-frameless-monitor',
    categorySlug: 'electronics',
    subcategorySlug: 'monitors',
    description: 'Stunning 3840x2160 IPS panel with 99% sRGB color gamut, dual HDMI 2.0, DisplayPort, built-in speakers, and blue light filter.',
    price: 21999,
    discountPercent: 22,
    stock: 18,
    rating: 4.7,
    reviewCount: 74,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Rugged Waterproof Bluetooth 20W Portable Speaker',
    slug: 'rugged-waterproof-bluetooth-speaker',
    categorySlug: 'electronics',
    subcategorySlug: 'speakers',
    description: 'IPX7 waterproof outdoor Bluetooth speaker with punchy bass, TWS dual pairing, and built-in mic for hands-free calling.',
    price: 2499,
    discountPercent: 35,
    stock: 45,
    rating: 4.5,
    reviewCount: 165,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Smart Fitness Tracker Watch with Bluetooth Calling (1.8" HD)',
    slug: 'smart-fitness-tracker-watch',
    categorySlug: 'electronics',
    subcategorySlug: 'smart-watches',
    description: '1.85-inch curved display, 120+ sports modes, 24/7 SpO2 & heart rate monitor, sleep tracking, and IP68 dust & water resistance.',
    price: 1999,
    discountPercent: 50,
    stock: 65,
    rating: 4.4,
    reviewCount: 410,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&q=80&w=800'],
  },

  // 5. MOBILE ACCESSORIES
  {
    name: '20000mAh 22.5W Fast Charging Power Bank with Dual Output',
    slug: '20000mah-fast-power-bank-pd',
    categorySlug: 'mobile-accessories',
    subcategorySlug: 'power-banks',
    description: 'High-density lithium polymer battery with Power Delivery 3.0 and Quick Charge 3.0. Charges iPhones & Android devices simultaneously.',
    price: 1999,
    discountPercent: 30,
    stock: 55,
    rating: 4.5,
    reviewCount: 220,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1609592424074-8b65287f3bfa?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Heavy-Duty Shockproof Air-Cushion Armor Phone Case',
    slug: 'shockproof-air-cushion-phone-case',
    categorySlug: 'mobile-accessories',
    subcategorySlug: 'mobile-cases',
    description: 'Dual layer PC and flexible TPU hybrid cover with raised edges to safeguard camera lens and touchscreen from hard drops.',
    price: 399,
    discountPercent: 40,
    stock: 90,
    rating: 4.6,
    reviewCount: 180,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: '65W GaN Dual Port USB-C & USB-A Fast Wall Charger',
    slug: '65w-gan-fast-wall-charger',
    categorySlug: 'mobile-accessories',
    subcategorySlug: 'chargers',
    description: 'Next-gen Gallium Nitride (GaN) technology delivers high power in a pocket-sized design. Charges laptops, tablets, and phones.',
    price: 1499,
    discountPercent: 35,
    stock: 40,
    rating: 4.8,
    reviewCount: 135,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: '100W Braided USB-C to USB-C Fast Data Cable (2 Meters)',
    slug: '100w-braided-usbc-cable-2m',
    categorySlug: 'mobile-accessories',
    subcategorySlug: 'usb-cables',
    description: 'E-marker smart chip supports 20V/5A 100W PD superfast charging. Tested for over 25,000 bending cycles with aluminum alloy heads.',
    price: 499,
    discountPercent: 30,
    stock: 80,
    rating: 4.7,
    reviewCount: 260,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Adjustable Foldable Aluminum Desktop Phone & Tablet Stand',
    slug: 'adjustable-aluminum-phone-stand',
    categorySlug: 'mobile-accessories',
    subcategorySlug: 'mobile-stands',
    description: 'Ergonomic multi-angle dual-hinge mobile holder with non-slip silicone pads and cable pass-through cutout for desk use.',
    price: 349,
    discountPercent: 45,
    stock: 75,
    rating: 4.6,
    reviewCount: 195,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&q=80&w=800'],
  },

  // 6. FASHION
  {
    name: 'Pure Cotton Handcrafted Floral Printed Anarkali Kurta Set',
    slug: 'cotton-floral-anarkali-kurta-set',
    categorySlug: 'fashion',
    subcategorySlug: 'kurtis',
    description: 'Breathable 100% cambric cotton with traditional Sanganeri hand-block prints. Includes flared kurta, pants, and matching dupatta.',
    price: 1899,
    discountPercent: 35,
    stock: 45,
    rating: 4.7,
    reviewCount: 130,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Men Slim Fit 100% Combed Cotton Oxford Casual Shirt',
    slug: 'men-slim-fit-oxford-casual-shirt',
    categorySlug: 'fashion',
    subcategorySlug: 'shirts',
    description: 'Classic button-down collar Oxford shirt with soft touch feel and modern curved hemline. Perfect for casual meetings and dinner wear.',
    price: 1499,
    discountPercent: 40,
    stock: 50,
    rating: 4.5,
    reviewCount: 95,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Traditional Banarasi Soft Art Silk Festive Saree with Blouse Piece',
    slug: 'banarasi-soft-silk-festive-saree',
    categorySlug: 'fashion',
    subcategorySlug: 'sarees',
    description: 'Woven with intricate golden zari motifs across rich pallu and borders. Elegant drape suitable for Indian weddings and festivals.',
    price: 2499,
    discountPercent: 45,
    stock: 35,
    rating: 4.8,
    reviewCount: 180,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: "Men's Regular Fit Rugged Stretch Denim Jeans (Dark Indigo)",
    slug: 'mens-stretch-denim-jeans-indigo',
    categorySlug: 'fashion',
    subcategorySlug: 'jeans',
    description: 'Cotton elastane blend offering all-day flexibility and shape retention. Reinforced stitching and classic 5-pocket styling.',
    price: 1799,
    discountPercent: 30,
    stock: 60,
    rating: 4.4,
    reviewCount: 220,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: "Women's Floral Tiered Bohemian Maxi Summer Dress",
    slug: 'womens-floral-bohemian-maxi-dress',
    categorySlug: 'fashion',
    subcategorySlug: 'dresses',
    description: 'Flowy georgette fabric with comfortable lining, square neck, ruffled sleeves, and smocked bodice for effortless styling.',
    price: 1299,
    discountPercent: 35,
    stock: 40,
    rating: 4.6,
    reviewCount: 115,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&q=80&w=800'],
  },

  // 7. FOOTWEAR
  {
    name: 'Men Ultra-Lightweight Breathable Mesh Running Shoes',
    slug: 'men-ultralight-mesh-running-shoes',
    categorySlug: 'footwear',
    subcategorySlug: 'sports-shoes',
    description: 'High-rebound EVA sole with shock absorption cushion and breathable knit fabric upper. Ideal for 5K runs and daily gym sessions.',
    price: 2999,
    discountPercent: 40,
    stock: 45,
    rating: 4.6,
    reviewCount: 380,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Women Memory Foam Orthopedic Comfort Walking Sneakers',
    slug: 'women-memory-foam-walking-sneakers',
    categorySlug: 'footwear',
    subcategorySlug: 'womens-shoes',
    description: 'Slip-on design with orthopedic arch support memory foam insole. Reduces heel pressure during extended standing and walking.',
    price: 2299,
    discountPercent: 35,
    stock: 40,
    rating: 4.5,
    reviewCount: 195,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Handcrafted Genuine Leather Formal Oxford Lace-Up Shoes',
    slug: 'genuine-leather-formal-oxford-shoes',
    categorySlug: 'footwear',
    subcategorySlug: 'mens-shoes',
    description: 'Polished full-grain genuine leather with brogue detailing and anti-skid TPR sole. A distinguished footwear staple for corporate attire.',
    price: 3499,
    discountPercent: 30,
    stock: 25,
    rating: 4.7,
    reviewCount: 88,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Anti-Skid Waterproof Cushion Home & Outdoor Slides / Slippers',
    slug: 'anti-skid-waterproof-cushion-slides',
    categorySlug: 'footwear',
    subcategorySlug: 'slippers',
    description: 'Thick sole cloud slides made from high-density EVA. Non-slip textured base ideal for bathrooms, beaches, and daily casual wear.',
    price: 499,
    discountPercent: 40,
    stock: 80,
    rating: 4.4,
    reviewCount: 310,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Traditional Men Ethnic Kolhapuri Style Leather Sandals',
    slug: 'men-ethnic-kolhapuri-sandals',
    categorySlug: 'footwear',
    subcategorySlug: 'sandals',
    description: 'Authentic handcrafted ethnic toe-ring sandals with braided strap details. Perfect pairing for kurtas and wedding attires.',
    price: 1199,
    discountPercent: 25,
    stock: 35,
    rating: 4.5,
    reviewCount: 65,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1562273138-f46be4ebdf33?auto=format&fit=crop&q=80&w=800'],
  },

  // 8. BEAUTY & PERSONAL CARE
  {
    name: '15% Vitamin C & Hyaluronic Acid Glowing Face Serum (30ml)',
    slug: 'vitamin-c-hyaluronic-face-serum-30ml',
    categorySlug: 'beauty-personal-care',
    subcategorySlug: 'skin-care',
    description: 'Brightens skin tone, fades dark spots and sun damage. Non-greasy lightweight formulation enriched with pure ferulic acid.',
    price: 699,
    discountPercent: 20,
    stock: 80,
    rating: 4.6,
    reviewCount: 520,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Cold-Pressed Ayurvedic Onion & Bhringraj Anti-Hair Fall Oil (200ml)',
    slug: 'ayurvedic-onion-hair-oil-200ml',
    categorySlug: 'beauty-personal-care',
    subcategorySlug: 'hair-care',
    description: 'Infused with Red Onion seed oil, Bhringraj, Brahmi and Almond oil. Revitalizes roots, minimizes breakage, and adds deep shine.',
    price: 499,
    discountPercent: 15,
    stock: 95,
    rating: 4.5,
    reviewCount: 290,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1608248597369-24759657a876?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Matte Transferproof 12-Hour Long Stay Liquid Lipstick',
    slug: 'matte-transferproof-liquid-lipstick',
    categorySlug: 'beauty-personal-care',
    subcategorySlug: 'makeup',
    description: 'Intense pigmented Indian nude rose shade. Enriched with vitamin E to keep lips moisturized without feathering or cracking.',
    price: 549,
    discountPercent: 30,
    stock: 65,
    rating: 4.7,
    reviewCount: 380,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Broad Spectrum SPF 50 PA+++ Ultra-Light Gel Sunscreen (50g)',
    slug: 'broad-spectrum-spf50-gel-sunscreen-50g',
    categorySlug: 'beauty-personal-care',
    subcategorySlug: 'skin-care',
    description: 'Leaves zero white cast on Indian skin tones. Water-resistant formula with cica and green tea extract for soothing sun protection.',
    price: 449,
    discountPercent: 20,
    stock: 70,
    rating: 4.8,
    reviewCount: 230,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Natural Bamboo Charcoal & Neem Herbal Toothpaste (100g Pack of 2)',
    slug: 'charcoal-neem-herbal-toothpaste-2pack',
    categorySlug: 'beauty-personal-care',
    subcategorySlug: 'oral-care',
    description: 'Fluoride-free whitening toothpaste with activated charcoal, clove, and organic neem. Fights plaque and ensures fresh breath.',
    price: 299,
    discountPercent: 25,
    stock: 85,
    rating: 4.4,
    reviewCount: 140,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1559599101-f09722fb4948?auto=format&fit=crop&q=80&w=800'],
  },

  // 9. HOME & KITCHEN
  {
    name: 'Non-Stick Die-Cast Aluminum Granite Cookware Set (3 Pieces)',
    slug: 'granite-non-stick-cookware-set-3pc',
    categorySlug: 'home-kitchen',
    subcategorySlug: 'cookware',
    description: 'Includes 24cm Fry Pan, 24cm Kadhai with tempered glass lid, and 28cm Dosa Tawa. PFOA-free 5-layer German granite coating.',
    price: 3499,
    discountPercent: 50,
    stock: 25,
    rating: 4.7,
    reviewCount: 82,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: '100% Egyptian Cotton 300 TC King Bed Sheet with 2 Pillow Covers',
    slug: 'egyptian-cotton-300tc-bedsheet-set',
    categorySlug: 'home-kitchen',
    subcategorySlug: 'home-furnishing',
    description: 'Ultra-soft sateen weave breathable king size double bedsheet (108" x 108"). Colorfast and shrink-resistant Indian floral motif.',
    price: 2499,
    discountPercent: 40,
    stock: 35,
    rating: 4.5,
    reviewCount: 165,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'High-Back Ergonomic Breathable Mesh Desk Chair with Lumbar Support',
    slug: 'ergonomic-mesh-desk-chair-lumbar',
    categorySlug: 'home-kitchen',
    subcategorySlug: 'furniture',
    description: '3D adjustable armrests, heavy-duty nylon star base, Class 4 hydraulic piston, and 135-degree recline mechanism.',
    price: 7999,
    discountPercent: 25,
    stock: 18,
    rating: 4.8,
    reviewCount: 70,
    isFeatured: true,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1580481072645-022f9a6d83d0?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Airtight Stackable Food Storage Containers with Lids (Pack of 6)',
    slug: 'airtight-food-storage-containers-pack-6',
    categorySlug: 'home-kitchen',
    subcategorySlug: 'storage-organization',
    description: 'BPA-free crystal clear containers with silicone sealing ring and easy-snap locking clips. Keeps pulses, sugar, and flour moisture-free.',
    price: 1199,
    discountPercent: 35,
    stock: 60,
    rating: 4.6,
    reviewCount: 190,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1590736969955-71cc94801759?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Premium Opalware 33-Piece Dinnerware Service Set for 6',
    slug: 'opalware-33-piece-dinnerware-set',
    categorySlug: 'home-kitchen',
    subcategorySlug: 'dinnerware',
    description: 'Bone-ash free thermal shock resistant tableware with delicate floral prints. Microwave safe, dishwasher safe, and chip-resistant.',
    price: 2899,
    discountPercent: 30,
    stock: 22,
    rating: 4.7,
    reviewCount: 95,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1615865417491-9941019fbc00?auto=format&fit=crop&q=80&w=800'],
  },

  // 10. APPLIANCES
  {
    name: '750W Heavy Duty 3-Jar Stainless Steel Mixer Grinder',
    slug: '750w-heavy-duty-mixer-grinder',
    categorySlug: 'appliances',
    subcategorySlug: 'mixers-grinders',
    description: '100% copper motor with overload protection, 3 hardened stainless steel jars for wet grinding, dry spices, and chutney making.',
    price: 3299,
    discountPercent: 30,
    stock: 30,
    rating: 4.6,
    reviewCount: 240,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: '190L 4-Star Inverter Direct Cool Single Door Refrigerator',
    slug: '190l-inverter-single-door-refrigerator',
    categorySlug: 'appliances',
    subcategorySlug: 'refrigerators',
    description: 'Smart inverter compressor with stabilizer-free operation (90V-310V). Toughened glass shelves and base stand drawer for vegetables.',
    price: 15490,
    discountPercent: 20,
    stock: 12,
    rating: 4.7,
    reviewCount: 110,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: '7kg Fully Automatic Top Load Washing Machine with Smart Inverter',
    slug: '7kg-fully-automatic-top-load-washer',
    categorySlug: 'appliances',
    subcategorySlug: 'washing-machines',
    description: 'TurboDrum wash technology, stainless steel tub, 8 wash programs, child lock, and digital display with fuzzy logic.',
    price: 17990,
    discountPercent: 25,
    stock: 15,
    rating: 4.6,
    reviewCount: 150,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'BLDC Energy Saving 28W High-Speed Ceiling Fan with Remote',
    slug: 'bldc-energy-saving-ceiling-fan',
    categorySlug: 'appliances',
    subcategorySlug: 'fans',
    description: 'Saves up to 65% electricity compared to regular induction fans. 1200mm aerodynamically designed blades with timer and sleep mode.',
    price: 3199,
    discountPercent: 35,
    stock: 40,
    rating: 4.8,
    reviewCount: 215,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1565183997392-2f6f122e5912?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: '20L Convection Microwave Oven with 100 Indian Auto Cook Menus',
    slug: '20l-convection-microwave-oven',
    categorySlug: 'appliances',
    subcategorySlug: 'microwave-ovens',
    description: 'Bake, grill, reheat, and defrost with precision heating. Includes deodorizer and steam clean feature for effortless hygiene.',
    price: 8490,
    discountPercent: 28,
    stock: 20,
    rating: 4.5,
    reviewCount: 88,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?auto=format&fit=crop&q=80&w=800'],
  },

  // 11. BOOKS
  {
    name: 'Atomic Habits by James Clear (Paperback Special Edition)',
    slug: 'atomic-habits-james-clear-paperback',
    categorySlug: 'books',
    subcategorySlug: 'non-fiction-books',
    description: 'An easy & proven way to build good habits and break bad ones. International #1 bestseller with millions of copies sold.',
    price: 599,
    discountPercent: 25,
    stock: 50,
    rating: 4.9,
    reviewCount: 1450,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Indian Polity for Civil Services Examination (7th Edition)',
    slug: 'indian-polity-civil-services-7th-ed',
    categorySlug: 'books',
    subcategorySlug: 'competitive-exam-books',
    description: 'The definitive textbook for UPSC aspirants. Covers constitutional framework, fundamental rights, central administration, and amendments.',
    price: 895,
    discountPercent: 20,
    stock: 35,
    rating: 4.8,
    reviewCount: 420,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Data Structures & Algorithms in Java (Core Textbook)',
    slug: 'data-structures-algorithms-java-book',
    categorySlug: 'books',
    subcategorySlug: 'computer-tech-books',
    description: 'Comprehensive guide covering asymptotic analysis, dynamic programming, graph algorithms, and coding interview preparation.',
    price: 850,
    discountPercent: 20,
    stock: 30,
    rating: 4.7,
    reviewCount: 115,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'The Psychology of Money by Morgan Housel',
    slug: 'psychology-of-money-morgan-housel',
    categorySlug: 'books',
    subcategorySlug: 'non-fiction-books',
    description: 'Timeless lessons on wealth, greed, and happiness. 19 short stories exploring the strange ways people think about money.',
    price: 399,
    discountPercent: 30,
    stock: 65,
    rating: 4.8,
    reviewCount: 890,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Panchatantra Illustrated Moral Storybook for Children',
    slug: 'panchatantra-illustrated-moral-storybook',
    categorySlug: 'books',
    subcategorySlug: 'childrens-books',
    description: 'Hardcover compilation of 50 timeless moral fables with vivid full-color illustrations. Helps instill valuable life lessons.',
    price: 299,
    discountPercent: 20,
    stock: 40,
    rating: 4.6,
    reviewCount: 130,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=800'],
  },

  // 12. STATIONERY
  {
    name: 'Spiral Bound Ruled Subject Notebooks (Pack of 6, 180 Pages Each)',
    slug: 'spiral-bound-ruled-notebooks-pack-6',
    categorySlug: 'stationery',
    subcategorySlug: 'notebooks',
    description: 'High-opacity 70 GSM elemental chlorine-free paper. Sturdy poly cover with snag-free twin-wire binding.',
    price: 499,
    discountPercent: 20,
    stock: 60,
    rating: 4.6,
    reviewCount: 180,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Smooth Flow 0.7mm Waterproof Gel Ink Pens (Box of 10)',
    slug: 'smooth-flow-gel-ink-pens-box-10',
    categorySlug: 'stationery',
    subcategorySlug: 'pens',
    description: 'Japanese quick-drying waterproof ink formula that prevents smudges. Ergonomic textured rubber grip for fatigue-free exams.',
    price: 199,
    discountPercent: 15,
    stock: 100,
    rating: 4.7,
    reviewCount: 290,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Artist Grade 36-Color Watercolour Cakes Set with Brushes',
    slug: 'artist-grade-watercolour-cakes-36-set',
    categorySlug: 'stationery',
    subcategorySlug: 'art-supplies',
    description: 'Vibrant, high-pigment washable watercolor pans with mixing palette tray and nylon hair detail painting brushes.',
    price: 449,
    discountPercent: 25,
    stock: 45,
    rating: 4.8,
    reviewCount: 95,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: '12-Digit Large Tilt Display Dual Powered Desktop Calculator',
    slug: '12-digit-desktop-calculator-dual-power',
    categorySlug: 'stationery',
    subcategorySlug: 'office-supplies',
    description: 'Solar & battery dual power with auto power-off. Responsive computer-style responsive keys and tax calculation shortcuts.',
    price: 389,
    discountPercent: 20,
    stock: 55,
    rating: 4.5,
    reviewCount: 140,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Ergonomic Waterproof 3-Compartment School & College Bag',
    slug: 'ergonomic-waterproof-college-bag',
    categorySlug: 'stationery',
    subcategorySlug: 'school-office-bags',
    description: 'Spacious 32L backpack with padded laptop sleeve, bottle pockets, rain cover, and breathable back airflow padding.',
    price: 1299,
    discountPercent: 40,
    stock: 40,
    rating: 4.6,
    reviewCount: 210,
    isFeatured: true,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800'],
  },

  // 13. TOYS & GAMES
  {
    name: 'STEM 6-in-1 Solar & Battery Powered DIY Robot Building Kit',
    slug: 'stem-solar-robot-building-kit',
    categorySlug: 'toys-games',
    subcategorySlug: 'educational-toys',
    description: 'Engaging educational engineering toy for kids aged 8+. Builds 6 working motorized robotic models teaching renewable energy.',
    price: 999,
    discountPercent: 30,
    stock: 35,
    rating: 4.7,
    reviewCount: 110,
    isFeatured: true,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1535378917042-10a22c95931a?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Handcrafted Wooden Foldable Chess Board Set with Magnetic Pieces',
    slug: 'wooden-foldable-chess-board-set',
    categorySlug: 'toys-games',
    subcategorySlug: 'board-games',
    description: '12" x 12" polished sheesham and maple wood chess set with internal velvet storage slots for all 32 carved magnetic chessmen.',
    price: 1499,
    discountPercent: 35,
    stock: 25,
    rating: 4.8,
    reviewCount: 165,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'High-Speed 2.4GHz 4WD Off-Road RC Rock Crawler Monster Truck',
    slug: 'rc-rock-crawler-monster-truck',
    categorySlug: 'toys-games',
    subcategorySlug: 'rc-toys',
    description: 'Dual motors, metal suspension shock absorbers, anti-skid rubber tires, and rechargeable lithium battery for all-terrain climbing.',
    price: 1899,
    discountPercent: 40,
    stock: 30,
    rating: 4.5,
    reviewCount: 140,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: '1000-Piece Precision Cut Himalayan Valley Scenic Jigsaw Puzzle',
    slug: '1000-piece-himalayan-jigsaw-puzzle',
    categorySlug: 'toys-games',
    subcategorySlug: 'puzzles',
    description: 'Sturdy recycled blue board puzzle with glare-free matte print and 1:1 reference bonus poster. Enhances focus and spatial reasoning.',
    price: 699,
    discountPercent: 25,
    stock: 40,
    rating: 4.6,
    reviewCount: 85,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1558060370-d644479cb6f7?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Interactive Musical Animal Sound Activity Walker for Toddlers',
    slug: 'musical-activity-walker-toddlers',
    categorySlug: 'toys-games',
    subcategorySlug: 'baby-toys-early',
    description: 'Helps babies take stable first steps with textured wheels and easy-grasp handle. Detachable activity panel with piano keys and gears.',
    price: 1799,
    discountPercent: 30,
    stock: 20,
    rating: 4.7,
    reviewCount: 75,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=800'],
  },

  // 14. BABY PRODUCTS
  {
    name: '100% Organic Cotton Unisex Baby Rompers (Pack of 3)',
    slug: 'organic-cotton-baby-rompers-pack-3',
    categorySlug: 'baby-products',
    subcategorySlug: 'baby-clothing',
    description: 'Hypoallergenic combed cotton with nickel-free crotch snap buttons for effortless diaper changes. Soft and gentle on infant skin.',
    price: 899,
    discountPercent: 30,
    stock: 45,
    rating: 4.8,
    reviewCount: 160,
    isFeatured: true,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Premium Ultra-Dry Pants Style Diapers - Medium (72 Count)',
    slug: 'ultra-dry-pants-diapers-medium-72',
    categorySlug: 'baby-products',
    subcategorySlug: 'baby-diapers',
    description: '12-hour leak lock protection with 3D bubble gel core and wetness indicator. Infused with mild aloe vera lotion to prevent rashes.',
    price: 949,
    discountPercent: 20,
    stock: 65,
    rating: 4.7,
    reviewCount: 310,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Tear-Free Gentle Nourishing Baby Body Wash & Shampoo (400ml)',
    slug: 'tear-free-gentle-baby-body-wash-400ml',
    categorySlug: 'baby-products',
    subcategorySlug: 'baby-care',
    description: 'Dermatologically tested pH 5.5 balanced baby cleanser with calendula and natural chamomile extracts. 100% soap and paraben free.',
    price: 399,
    discountPercent: 15,
    stock: 55,
    rating: 4.8,
    reviewCount: 220,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'BPA-Free Anti-Colic Silicone Nipple Feeding Bottle (250ml)',
    slug: 'bpa-free-anti-colic-feeding-bottle-250ml',
    categorySlug: 'baby-products',
    subcategorySlug: 'feeding-accessories',
    description: 'Dual anti-colic air vent valves reduce swallowed air and colic distress. Wide-neck design for easy formula preparation and cleaning.',
    price: 349,
    discountPercent: 25,
    stock: 50,
    rating: 4.6,
    reviewCount: 135,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Pure Multigrain Baby Cereal with Banana & Apple (300g)',
    slug: 'pure-multigrain-baby-cereal-300g',
    categorySlug: 'baby-products',
    subcategorySlug: 'baby-food',
    description: 'Fortified with iron, calcium, vitamin D, and zinc. Smooth texture suitable for babies from 8 to 24 months. Zero added artificial sugar.',
    price: 295,
    discountPercent: 10,
    stock: 70,
    rating: 4.7,
    reviewCount: 185,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1505253758473-96b3015f27eb?auto=format&fit=crop&q=80&w=800'],
  },

  // 15. SPORTS & FITNESS
  {
    name: 'Kashmir Willow Grade 1 Full Size Leather Cricket Bat',
    slug: 'kashmir-willow-grade1-cricket-bat',
    categorySlug: 'sports-fitness',
    subcategorySlug: 'cricket-gear',
    description: 'Selected air-dried Kashmir willow with massive edges and curved profile. Fitted with multi-piece Singapore cane handle for superior shock absorption.',
    price: 2299,
    discountPercent: 35,
    stock: 25,
    rating: 4.7,
    reviewCount: 175,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Eco-Friendly High-Density 6mm Dual Color TPE Yoga Mat',
    slug: 'high-density-6mm-tpe-yoga-mat',
    categorySlug: 'sports-fitness',
    subcategorySlug: 'yoga-fitness',
    description: 'Anti-tear non-slip alignment texture with optimal joint cushioning. Comes with carry strap for gym, home, and outdoor yoga.',
    price: 999,
    discountPercent: 40,
    stock: 60,
    rating: 4.8,
    reviewCount: 310,
    isFeatured: true,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Cast Iron Hex Dumbbells Set with Rubber Coating (Pair of 5kg)',
    slug: 'rubber-coated-hex-dumbbells-5kg-pair',
    categorySlug: 'sports-fitness',
    subcategorySlug: 'fitness-equipment',
    description: 'Solid cast iron heads encased in heavy-duty virgin rubber to prevent rolling and floor damage. Contoured knurled chrome handles.',
    price: 1899,
    discountPercent: 30,
    stock: 35,
    rating: 4.6,
    reviewCount: 190,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1586401100295-7a8096fd231a?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'FIFA Standard Thermal Bonded Size 5 Match Football',
    slug: 'fifa-standard-size-5-match-football',
    categorySlug: 'sports-fitness',
    subcategorySlug: 'football-gear',
    description: 'Seamless thermal bonding technology for zero water absorption and predictable trajectory. Butyl bladder ensures long air retention.',
    price: 1199,
    discountPercent: 35,
    stock: 40,
    rating: 4.5,
    reviewCount: 120,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'High Tension Carbon Fiber Badminton Racket with Full Cover',
    slug: 'carbon-fiber-badminton-racket',
    categorySlug: 'sports-fitness',
    subcategorySlug: 'badminton-gear',
    description: 'Ultra-light 82g isometric frame strung to 28 lbs tension. Built-in T-joint delivers maximum smash power and rapid swing speed.',
    price: 1699,
    discountPercent: 40,
    stock: 30,
    rating: 4.7,
    reviewCount: 145,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&q=80&w=800'],
  },

  // 16. JEWELLERY & ACCESSORIES
  {
    name: 'Traditional 24K Gold Plated Kundan Choker Necklace Set',
    slug: '24k-gold-plated-kundan-choker-set',
    categorySlug: 'jewellery-accessories',
    subcategorySlug: 'jewellery-necklaces',
    description: 'Handset faux Kundan stones with green bead drops. Includes matching jhumka earrings and maang tikka for bridal and festive occasions.',
    price: 1999,
    discountPercent: 50,
    stock: 30,
    rating: 4.7,
    reviewCount: 125,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Chronograph Stainless Steel Water Resistant Watch for Men',
    slug: 'chronograph-watch-men-steel',
    categorySlug: 'jewellery-accessories',
    subcategorySlug: 'jewellery-watches',
    description: 'Japanese quartz movement, mineral glass dial, date display, 50m water resistance, and durable stainless steel chain.',
    price: 4500,
    discountPercent: 30,
    stock: 25,
    rating: 4.7,
    reviewCount: 150,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Genuine Leather RFID Blocking Bi-Fold Wallet for Men',
    slug: 'genuine-leather-rfid-wallet-men',
    categorySlug: 'jewellery-accessories',
    subcategorySlug: 'jewellery-wallets',
    description: 'Crafted from top-grain leather with 8 card slots, 2 currency compartments, and hidden coin pocket. RFID protection against scanning.',
    price: 1299,
    discountPercent: 35,
    stock: 65,
    rating: 4.6,
    reviewCount: 280,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Polarized UV400 Protection Metal Frame Aviator Sunglasses',
    slug: 'polarized-aviator-sunglasses-uv400',
    categorySlug: 'jewellery-accessories',
    subcategorySlug: 'jewellery-sunglasses',
    description: 'Lightweight alloy metal frame with glare-reducing polarized lenses. Protects eyes from 100% harmful UVA and UVB rays.',
    price: 1599,
    discountPercent: 50,
    stock: 40,
    rating: 4.4,
    reviewCount: 180,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: "Women's Designer Vegan Leather Satchel Shoulder Handbag",
    slug: 'womens-vegan-leather-satchel-handbag',
    categorySlug: 'jewellery-accessories',
    subcategorySlug: 'jewellery-handbags',
    description: 'Spacious main compartment with magnetic flap, interior zipper pockets, top handle, and detachable adjustable shoulder strap.',
    price: 2199,
    discountPercent: 40,
    stock: 35,
    rating: 4.6,
    reviewCount: 160,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&q=80&w=800'],
  },

  // 17. AUTOMOTIVE
  {
    name: 'All-Weather 7D Heavy Duty Custom-Fit Car Foot Mats (Set of 5)',
    slug: '7d-heavy-duty-car-foot-mats',
    categorySlug: 'automotive',
    subcategorySlug: 'car-accessories',
    description: 'Raised edges prevent mud, spills, and dust from staining car carpet. Waterproof, odor-free, with detachable anti-slip curly mat layer.',
    price: 2999,
    discountPercent: 35,
    stock: 25,
    rating: 4.6,
    reviewCount: 110,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'ISI & DOT Certified Full Face Aerodynamic Motorcycle Helmet',
    slug: 'full-face-aerodynamic-motorcycle-helmet',
    categorySlug: 'automotive',
    subcategorySlug: 'helmets',
    description: 'High-impact ABS shell with EPS multi-density safety liner, scratch-resistant quick-release visor, and dynamic ventilation channels.',
    price: 1899,
    discountPercent: 25,
    stock: 30,
    rating: 4.8,
    reviewCount: 240,
    isFeatured: true,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Ultra-Plush 800 GSM Microfiber Car Drying & Detailing Towels (Pack of 3)',
    slug: '800gsm-microfiber-car-detailing-towels',
    categorySlug: 'automotive',
    subcategorySlug: 'car-care',
    description: 'Scratch-free edgeless dual-sided microfiber cloth holding up to 10x its weight in water. Ideal for waterless washing and buffing waxes.',
    price: 499,
    discountPercent: 30,
    stock: 75,
    rating: 4.7,
    reviewCount: 320,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1607860108855-64acf2078ed9?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Portable 12V 150 PSI Digital Auto-Cut Tire Inflator Air Pump',
    slug: 'portable-digital-tire-inflator-12v',
    categorySlug: 'automotive',
    subcategorySlug: 'vehicle-electronics',
    description: 'Plugs into car cigarette lighter. Features bright LED emergency work light, digital pressure preset, and auto shut-off upon reaching target PSI.',
    price: 1999,
    discountPercent: 40,
    stock: 35,
    rating: 4.5,
    reviewCount: 160,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Universal Waterproof Motorcycle Body Cover with Mirror Pockets',
    slug: 'waterproof-motorcycle-body-cover',
    categorySlug: 'automotive',
    subcategorySlug: 'bike-accessories',
    description: 'Heavy 190T polyester fabric protects bike against UV rays, rain, dust, and scratches. Equipped with bottom lock clip to withstand winds.',
    price: 499,
    discountPercent: 35,
    stock: 50,
    rating: 4.4,
    reviewCount: 85,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1558981854-383395b0f459?auto=format&fit=crop&q=80&w=800'],
  },

  // 18. HOME IMPROVEMENT
  {
    name: '108-Piece Complete Household Hand Tool Kit with Hard Case',
    slug: '108-piece-complete-household-tool-kit',
    categorySlug: 'home-improvement',
    subcategorySlug: 'diy-tools',
    description: 'Forged chrome vanadium tools including claw hammer, precision screwdrivers, adjustable wrench, digital voltage tester, and pliers.',
    price: 2499,
    discountPercent: 35,
    stock: 30,
    rating: 4.7,
    reviewCount: 140,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Heavy Duty 4-Socket Spike Guard Extension Board with 2 USB Ports (3m)',
    slug: 'heavy-duty-spike-guard-extension-board',
    categorySlug: 'home-improvement',
    subcategorySlug: 'electrical-supplies',
    description: 'Fire-retardant ABS body with thermal circuit breaker, individual LED switches, and surge suppression protecting smart TVs and computers.',
    price: 699,
    discountPercent: 30,
    stock: 70,
    rating: 4.6,
    reviewCount: 290,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Energy Efficient 10W B22 LED Cool Day White Bulbs (Pack of 6)',
    slug: 'energy-efficient-10w-led-bulbs-pack-6',
    categorySlug: 'home-improvement',
    subcategorySlug: 'lighting-fixtures',
    description: '1050 Lumens per bulb with 25,000-hour rated lifespan and wide 240-degree beam spread. 85% energy savings over incandescent lamps.',
    price: 499,
    discountPercent: 25,
    stock: 80,
    rating: 4.5,
    reviewCount: 410,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1517991104123-1d56a6e81ed9?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: '5-Piece Heavy Duty Home Garden Hand Tool Set with Bypass Pruner',
    slug: '5-piece-garden-hand-tool-set',
    categorySlug: 'home-improvement',
    subcategorySlug: 'gardening-supplies',
    description: 'Rust-resistant carbon steel trowel, cultivator, transplanter, weeder, and sharp SK5 steel pruning shear with ergonomic grips.',
    price: 799,
    discountPercent: 35,
    stock: 45,
    rating: 4.7,
    reviewCount: 115,
    isFeatured: true,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'High-Pressure 5-Mode Chrome Plated Handheld Shower Head with Hose',
    slug: 'high-pressure-handheld-shower-head',
    categorySlug: 'home-improvement',
    subcategorySlug: 'hardware-fixtures',
    description: 'Micro-hole nozzle technology boosts water pressure while cutting water consumption by 30%. Includes 1.5m stainless steel anti-twist hose.',
    price: 899,
    discountPercent: 40,
    stock: 40,
    rating: 4.4,
    reviewCount: 95,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=800'],
  },

  // 19. PET SUPPLIES
  {
    name: 'Pedigree Complete Real Chicken & Rice Adult Dry Dog Food (3kg)',
    slug: 'pedigree-chicken-rice-dog-food-3kg',
    categorySlug: 'pet-supplies',
    subcategorySlug: 'pet-food',
    description: 'Wholesome balanced nutrition containing 20% crude protein, omega-6 fatty acids, and zinc for a healthy coat and strong immune system.',
    price: 849,
    discountPercent: 12,
    stock: 50,
    rating: 4.7,
    reviewCount: 380,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Whiskas Ocean Fish in Gravy Adult Wet Cat Food (Pack of 12 x 85g)',
    slug: 'whiskas-ocean-fish-wet-cat-food-12pack',
    categorySlug: 'pet-supplies',
    subcategorySlug: 'pet-food',
    description: 'Tender fish morsels cooked in appetizing gravy. Provides essential taurine for eyesight, urinary tract health, and shiny fur.',
    price: 540,
    discountPercent: 10,
    stock: 60,
    rating: 4.8,
    reviewCount: 290,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Indestructible Natural Rubber Chew Ball & Squeaky Rope Dog Toy Set',
    slug: 'rubber-chew-ball-rope-dog-toy-set',
    categorySlug: 'pet-supplies',
    subcategorySlug: 'pet-toys',
    description: 'Non-toxic natural rubber designed for aggressive chewers. Helps clean teeth, massage gums, and satisfy chewing instincts.',
    price: 399,
    discountPercent: 30,
    stock: 70,
    rating: 4.5,
    reviewCount: 150,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Stainless Steel Double Pet Feeding Bowls with Non-Spill Silicone Mat',
    slug: 'stainless-steel-double-pet-bowls',
    categorySlug: 'pet-supplies',
    subcategorySlug: 'dog-supplies',
    description: 'Removable rust-resistant food grade stainless steel bowls. Raised silicone base catches food spills and prevents sliding on tiles.',
    price: 699,
    discountPercent: 30,
    stock: 45,
    rating: 4.6,
    reviewCount: 110,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Herbal Neem & Oatmeal Coat Deodorizing Pet Shampoo (500ml)',
    slug: 'herbal-neem-oatmeal-pet-shampoo-500ml',
    categorySlug: 'pet-supplies',
    subcategorySlug: 'pet-grooming',
    description: 'Soothes dry itchy skin, repels fleas and ticks naturally, and leaves long-lasting refreshing green apple aroma on dog & cat fur.',
    price: 349,
    discountPercent: 20,
    stock: 55,
    rating: 4.6,
    reviewCount: 135,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&q=80&w=800'],
  },

  // 20. TRAVEL
  {
    name: '35L Water-Resistant Hiking & Trekking Rucksack with Rain Cover',
    slug: '35l-water-resistant-hiking-rucksack',
    categorySlug: 'travel',
    subcategorySlug: 'travel-backpacks',
    description: 'Ripstop honeycomb nylon with reinforced bar-tacks. Features trekking pole loops, chest whistle strap, and concealed bottom rain cover.',
    price: 1899,
    discountPercent: 40,
    stock: 35,
    rating: 4.7,
    reviewCount: 220,
    isFeatured: true,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: '3-Piece Lightweight Polycarbonate Luggage Trolley Set (Cabin, Med, Large)',
    slug: '3-piece-polycarbonate-luggage-trolley-set',
    categorySlug: 'travel',
    subcategorySlug: 'travel-suitcases',
    description: 'Scratch-resistant hard shell, TSA-approved combination lock, 360-degree silent dual spinner wheels, and telescopic aluminum handle.',
    price: 8999,
    discountPercent: 45,
    stock: 18,
    rating: 4.8,
    reviewCount: 95,
    isFeatured: true,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'All-in-One Universal International Travel Power Adapter (Dual USB)',
    slug: 'universal-international-travel-adapter',
    categorySlug: 'travel',
    subcategorySlug: 'travel-accessories',
    description: 'Covers over 150 countries with US/EU/UK/AUS plugs. Built-in 6A fuse safety shutter prevents overcharge and electric shock.',
    price: 649,
    discountPercent: 35,
    stock: 65,
    rating: 4.6,
    reviewCount: 310,
    isFeatured: false,
    isNewArrival: true,
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: '6-Piece Compression Packing Cubes Luggage Organizer Set',
    slug: '6-piece-compression-packing-cubes',
    categorySlug: 'travel',
    subcategorySlug: 'travel-organizers',
    description: 'Compresses clothing volume by up to 40% with dual zipper system. Includes shoe bag, laundry bag, and breathable mesh organizers.',
    price: 799,
    discountPercent: 35,
    stock: 50,
    rating: 4.7,
    reviewCount: 180,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&q=80&w=800'],
  },
  {
    name: 'Ergonomic Memory Foam Flight Travel Neck Pillow with Eye Mask',
    slug: 'ergonomic-memory-foam-neck-pillow',
    categorySlug: 'travel',
    subcategorySlug: 'travel-accessories',
    description: '360-degree head support relieves cervical tension on long flights and road trips. Washable sweat-resistant magnetic therapy cloth cover.',
    price: 599,
    discountPercent: 40,
    stock: 60,
    rating: 4.5,
    reviewCount: 145,
    isFeatured: false,
    isNewArrival: false,
    images: ['https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&q=80&w=800'],
  },
];

async function main() {
  console.log('Seeding YashodhaMart database...');

  // 1. Create Demo Admin
  const adminPasswordHash = await bcrypt.hash('Admin12345!', 10);
  const admin = await prisma.admin.upsert({
    where: { email: 'admin@yashodhamart.com' },
    update: {},
    create: {
      name: 'Yashodha Admin',
      email: 'admin@yashodhamart.com',
      passwordHash: adminPasswordHash,
      role: 'ADMIN',
    },
  });
  console.log('Admin ready:', admin.email);

  // 2. Create Demo User
  const userPasswordHash = await bcrypt.hash('User12345!', 10);
  const user = await prisma.user.upsert({
    where: { email: 'user@yashodhamart.com' },
    update: {},
    create: {
      name: 'Rahul Sharma',
      email: 'user@yashodhamart.com',
      phone: '9876543210',
      passwordHash: userPasswordHash,
      role: 'USER',
    },
  });
  console.log('User ready:', user.email);

  // 3. Create or find Default Address for User
  let address = await prisma.address.findFirst({
    where: { userId: user.id },
  });

  if (!address) {
    address = await prisma.address.create({
      data: {
        userId: user.id,
        fullName: 'Rahul Sharma',
        phone: '9876543210',
        houseBuilding: 'Flat 402, Sunshine Apartments',
        street: 'MG Road, Outer Ring Road',
        area: 'Indiranagar',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560038',
        isDefault: true,
      },
    });
  }

  // 4. Upsert 20 Major Categories and Subcategories
  const categoryMap: Record<string, string> = {};
  const subcategoryMap: Record<string, string> = {};

  for (const catDef of CATEGORIES_DATA) {
    // Upsert parent category
    const parentCategory = await prisma.category.upsert({
      where: { slug: catDef.slug },
      update: {
        name: catDef.name,
        description: catDef.description,
        image: catDef.image,
        isActive: true,
      },
      create: {
        name: catDef.name,
        slug: catDef.slug,
        description: catDef.description,
        image: catDef.image,
        isActive: true,
      },
    });
    categoryMap[catDef.slug] = parentCategory.id;

    // Upsert subcategories
    for (const subDef of catDef.subcategories) {
      const subCategory = await prisma.category.upsert({
        where: { slug: subDef.slug },
        update: {
          name: subDef.name,
          description: subDef.description,
          parentId: parentCategory.id,
          isActive: true,
        },
        create: {
          name: subDef.name,
          slug: subDef.slug,
          description: subDef.description,
          parentId: parentCategory.id,
          isActive: true,
        },
      });
      subcategoryMap[subDef.slug] = subCategory.id;
    }
  }

  console.log(`Seeded 20 major categories and ${Object.keys(subcategoryMap).length} subcategories.`);

  // 5. Seed 105+ Realistic Products across all categories
  let productCount = 0;
  for (const prod of PRODUCTS_DATA) {
    const parentCatId = categoryMap[prod.categorySlug];
    const subCatId = subcategoryMap[prod.subcategorySlug] || null;

    if (!parentCatId) {
      console.warn(`Category slug ${prod.categorySlug} not found for product ${prod.name}`);
      continue;
    }

    await prisma.product.upsert({
      where: { slug: prod.slug },
      update: {
        name: prod.name,
        description: prod.description,
        price: prod.price,
        discountPercent: prod.discountPercent,
        stock: prod.stock,
        rating: prod.rating,
        reviewCount: prod.reviewCount,
        isFeatured: prod.isFeatured,
        isNewArrival: prod.isNewArrival,
        isActive: true,
        categoryId: parentCatId,
        subcategoryId: subCatId,
        images: JSON.stringify(prod.images),
      },
      create: {
        name: prod.name,
        slug: prod.slug,
        description: prod.description,
        price: prod.price,
        discountPercent: prod.discountPercent,
        stock: prod.stock,
        rating: prod.rating,
        reviewCount: prod.reviewCount,
        isFeatured: prod.isFeatured,
        isNewArrival: prod.isNewArrival,
        isActive: true,
        categoryId: parentCatId,
        subcategoryId: subCatId,
        images: JSON.stringify(prod.images),
      },
    });
    productCount++;
  }

  console.log(`Seeded ${productCount} sample products across all 20 categories.`);

  // Clean up any legacy products not in current catalog
  const validProdSlugs = PRODUCTS_DATA.map((p) => p.slug);
  const defaultProduct = await prisma.product.findFirst({ where: { slug: validProdSlugs[0] } });

  if (defaultProduct) {
    const legacyProducts = await prisma.product.findMany({
      where: { slug: { notIn: validProdSlugs } },
      select: { id: true, name: true }
    });

    for (const leg of legacyProducts) {
      const firstWord = leg.name.split(' ')[0] || '';
      const matched = (firstWord ? await prisma.product.findFirst({
        where: {
          slug: { in: validProdSlugs },
          name: { contains: firstWord }
        }
      }) : null) || defaultProduct;

      await prisma.orderItem.updateMany({
        where: { productId: leg.id },
        data: {
          productId: matched.id,
          productName: matched.name,
          productImage: JSON.parse(matched.images)[0] || '',
        }
      });
    }

    await prisma.cartItem.deleteMany({
      where: { product: { slug: { notIn: validProdSlugs } } },
    });
    await prisma.wishlistItem.deleteMany({
      where: { product: { slug: { notIn: validProdSlugs } } },
    });
    await prisma.review.deleteMany({
      where: { product: { slug: { notIn: validProdSlugs } } },
    });
    await prisma.product.deleteMany({
      where: { slug: { notIn: validProdSlugs } },
    });
  }

  // Clean up any obsolete categories that are no longer in CATEGORIES_DATA
  const validCatSlugs = CATEGORIES_DATA.map((c) => c.slug);
  const validSubSlugs = CATEGORIES_DATA.flatMap((c) => c.subcategories.map((s) => s.slug));
  await prisma.category.deleteMany({
    where: { slug: { notIn: [...validCatSlugs, ...validSubSlugs] } },
  });


  // 6. Ensure at least one sample order exists for demo testing
  const existingOrder = await prisma.order.findFirst({
    where: { userId: user.id },
  });

  if (!existingOrder) {
    const sampleProduct = await prisma.product.findFirst({
      where: { isActive: true },
    });

    if (sampleProduct) {
      const effPrice = Math.round(sampleProduct.price * (1 - sampleProduct.discountPercent / 100));
      const sampleImg = JSON.parse(sampleProduct.images)[0] || '';

      await prisma.order.create({
        data: {
          orderNumber: 'YM-ORD-100291',
          userId: user.id,
          totalAmount: sampleProduct.price,
          discountAmount: Math.round(sampleProduct.price * (sampleProduct.discountPercent / 100)),
          deliveryFee: 0,
          finalAmount: effPrice,
          paymentMethod: 'QR_DEMO',
          paymentStatus: 'PAID',
          transactionReference: 'UPI-DEMO-994821',
          paidAt: new Date(),
          orderStatus: 'Delivered',
          shippingAddress: JSON.stringify(address),
          items: {
            create: [
              {
                productId: sampleProduct.id,
                productName: sampleProduct.name,
                productImage: sampleImg,
                price: effPrice,
                quantity: 1,
                totalPrice: effPrice,
              },
            ],
          },
        },
      });
      console.log('Sample demo order created.');
    }
  }

  console.log('Database seeding finished successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
